Linear regression
exasol/data-science-examples pull request #10
Opened 2019-08-15 13:13 UTC by AnastasiiaSergienko

2019-08-19 12:24 UTC, tkilias commented on tutorials/python/scikit-learn/regression/CsvImporter.py
> +    def __get_iterable_csv(self, connection, table_name, file_path, file_name):
the method name is outdated if you use the import command

2019-08-19 12:24 UTC, tkilias commented on tutorials/python/scikit-learn/regression/CsvImporter.py
> +    def __init__(self, dsn, user, password):
I am currently thinking about, if it would be better if assume a pyexasol connection as input or create each time a new one. The time to create new one is negligibly, but the DB has a limit of how many connections can be open. Furthermore, you currently force a commit with this connection, because at least at the close a commit will happen. So, I think it is a better idea to receive a connection as input and don't create it.

2019-08-19 12:24 UTC, tkilias commented on tutorials/python/scikit-learn/regression/CsvImporter.py
> +            + "' COLUMN SEPARATOR = ',' SKIP = 1  ERRORS INTO error_table (CURRENT_TIMESTAMP) REJECT LIMIT UNLIMITED ERRORS")
Depending on your intention for this class, we need a way to change the separators in import statement. If you want it to be a general and reusable class, we need these parameters. If it a specific class for this use case than its fine to hard code them, but it that case we actually could also add the schema definition here.

2019-08-19 13:50 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/CsvImporter.py
> +            + "' COLUMN SEPARATOR = ',' SKIP = 1  ERRORS INTO error_table (CURRENT_TIMESTAMP) REJECT LIMIT UNLIMITED ERRORS")
extracted as an argument

2019-08-19 14:09 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/CsvImporter.py
> +    def __init__(self, dsn, user, password):
I'll use a connection as an argument

2019-10-15 06:33 UTC, tkilias requested changes
See my inline comments. Style is in general excellent. I like that you use type-hints. The only changes we really need are for the transformer, see my comments. Most of the other comments are something we need to discuss and decide what we want to make out of your work, because I think, we might extract it into a data science library/toolbox. However, I don't know yet, how it would like. Possible ways are, external python scripts, like now, python UDFs which run the queries with pyexasol from inside the UDF or both? Lua scripts we already ruled out, I think. Then I need to hurry up with the python script support for Exasol which means pquery for the python UDFs.

2019-10-15 06:33 UTC, tkilias commented on tutorials/python/scikit-learn/regression/QueryGenerator.py
> +        return '1.00 * ("{column_name}" - MIN("{column_name}") OVER()) / (MAX("{column_name}") OVER () - MIN("{column_name}") OVER ()) AS "{column_name}"'.format(
I thought about this, we actually might need to persist min, max and likely other statistics for other scaling/normalization methods. For example, the standard scaler needs means and variance. We need to persist these statistics, for the same reasons, we need tables instead views  for the categories. These statistics might change with new data, but our model was trained on the statistics of the training data. If we change, now these statistics we actually change the scaled value for a given input value and the model might interpret this as a different input value. If you have a strong shift in the input statistics you normally need to retrain the model with the new data and new statistics. In the future, we might need to implement a way to check the statistics shift and think about if we can update the statistics and also the model or if we need to regenerate and retrain them from scratch.

Further, we might actually generate a config file from the category mapping and scaling/normalization statistics which allows us to embed the transformations into the model. Such that, you don't need SQL to make transformations and can export the model or use it on a stream of data instead of a table.

2019-10-15 06:33 UTC, tkilias commented on tutorials/python/scikit-learn/regression/ColumnStatisticCollector.py
> +        result_set = connection.export_to_pandas(
At some point in the future, we might need here multi-column statistics, for example avg(delay) per month, day, airport, state, ...

2019-10-15 06:33 UTC, tkilias commented on tutorials/python/scikit-learn/regression/SmallDataTransformer.py
> +class SmallDataTransformer:
We need to serialize the scaler and encoder, such that you can reuse them later and don't have refit them every time.

2019-10-15 06:33 UTC, tkilias commented on tutorials/python/scikit-learn/regression/SmallDataTransformer.py
> +                output[column_name] = LabelEncoder().fit_transform(column)
This one, I don't understand. I probably need to check what the LabelEncoder does.

2019-10-15 06:33 UTC, tkilias commented on tutorials/python/scikit-learn/regression/QueryGenerator.py
> +    def generate_final_query(self, tables_list: List[str], final_table_name: str, origin_table_name: str,
Might be good to extract the query parts into methods and give them names

2019-10-29 15:05 UTC, tkilias commented on tutorials/python/scikit-learn/regression/regression_tutorial.ipynb
> +    "<img src=\"img/img1.png\">"
@AnastasiiaSergienko The number of flights per week day is probably not the most interesting chart. I think the flights per FIP might be more interesting.

2020-02-12 14:02 UTC, tkilias requested changes

2020-02-12 14:02 UTC, tkilias commented on tutorials/python/scikit-learn/regression/LinearRegressionPrediction.py
> +    def __create_query(self, table_name: str, columns_list: list, split: str) -> str:
it might be a good idea if we would be able to fetch batches from the database for example by fetching specific tuples via primary key.

`SELECT {x_columns_string} FROM {table_name} WHERE primary_key in (1,2,3,4,5,...)`

Before that you could fetch all primary keys from the database with

`SELECT primary_key FROM {table_name} WHERE split = '{split}'`

You can than get batches of these primary keys with:
```
from sklearn.utils import shuffle
df = shuffle(df)
for i in range(0,len(df),batch_size):
	batch_of_pk=df.iloc[i:i+batch_size]
```

2020-02-13 08:22 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/regression_tutorial.ipynb
> +    "<img src=\"img/img1.png\">"
Changed the image to the flights per FIP

2020-02-13 08:40 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/LinearRegressionPrediction.py
> +        categorical_columns_date_frame = all_columns_train_data_frame.filter(x_columns_categorical_list, axis=1)
fixed

2020-02-13 08:40 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/LinearRegressionPrediction.py
> +        numerical_columns_data_frame = all_columns_train_data_frame.filter(x_columns_numerical_list, axis=1)
fixed

2020-02-13 09:02 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/LinearRegressionPrediction.py
> +            categories.append(numpy.arange(value + 1))
changed this code

2020-02-13 09:50 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/LargeDataTransformer.py
> +                'CREATE OR REPLACE VIEW {column_name}_categories AS SELECT rownum - 1 AS id, {column_name} FROM (SELECT DISTINCT {column_name} FROM {origin_table_name})'
fixed

2020-02-13 10:11 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/ColumnStatisticCollector.py
> +        min_value = self.__get_query_result(connection, 'SELECT MIN("{column_name}") from {table_name};'
It's just strange names, actually, I applied this method to all the columns, not only categorical. Renamed them properly

2020-02-13 11:16 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/SmallDataTransformer.py
> +class SmallDataTransformer:
I read somewhere on the internet that it's a good practice to create a new Encoder for each column. But I can add them as class variables if you think that it would be better. By the way, I rewrote this class quite a lot. Please check it one more time taler

2020-02-13 11:36 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/SmallDataTransformer.py
> +                output[column_name] = LabelEncoder().fit_transform(column)
I changed this piece of code. I think it's more clear now

2020-02-14 07:44 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/QueryGenerator.py
> +    def generate_final_query(self, tables_list: List[str], final_table_name: str, origin_table_name: str,
Refactored this logic

2020-02-20 15:50 UTC, tkilias requested changes

2020-02-20 15:50 UTC, tkilias commented on tutorials/python/scikit-learn/regression/regression_tutorial.ipynb
> +{
<ul><li>Actually, 80 GB would be possible to work with on a server, so maybe say, that it isn't feasible to work with 80Gb in pandas on your Notebook</li><li>Type: directly importing <strong>is</strong> as a Pandas DataFrame </li></ul><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/exasol/data-science-examples/pull/10/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2020-02-20 15:50 UTC, tkilias commented on tutorials/python/scikit-learn/regression/regression_tutorial.ipynb
> +{
<p>maybe link to the file, instead of copying it to the notebook</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/exasol/data-science-examples/pull/10/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2020-02-20 15:50 UTC, tkilias commented on tutorials/python/scikit-learn/regression/regression_tutorial.ipynb
> +{
<ul><li>Typo: which of them we would =&gt; which of them we would like to</li><li>repetition: which of them we would</li></ul>
<br/>

 _Reply via <a href='https://app.reviewnb.com/exasol/data-science-examples/pull/10/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='8'/>

2020-02-20 15:50 UTC, tkilias commented on tutorials/python/scikit-learn/regression/regression_tutorial.ipynb
> +{
<p>A small interpretation about what we can see on this graphic might be helpful. So, for example, what states are actually behind the FIPS with large values or small values.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/exasol/data-science-examples/pull/10/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='10'/>

2020-02-20 15:50 UTC, tkilias commented on tutorials/python/scikit-learn/regression/regression_tutorial.ipynb
> +{
<p>Can you add comments to the lines of the SQL what they actually do</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/exasol/data-science-examples/pull/10/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2020-02-20 15:50 UTC, tkilias commented on tutorials/python/scikit-learn/regression/regression_tutorial.ipynb
> +{
<ul><li>Before loading the data into the model, =&gt; we don't load data into a model, we train a model with data</li><li>See, my comments to the LabelEncoder in the code</li></ul>
<br/>

 _Reply via <a href='https://app.reviewnb.com/exasol/data-science-examples/pull/10/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='13'/>

2020-02-20 15:50 UTC, tkilias commented on tutorials/python/scikit-learn/regression/regression_tutorial.ipynb
> +{
<p>Maybe link only to the file</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/exasol/data-science-examples/pull/10/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='14'/>

2020-02-20 15:50 UTC, tkilias commented on tutorials/python/scikit-learn/regression/regression_tutorial.ipynb
> +{
<ul><li>but to do it without ready-to-use libraries. =&gt; however scalable and fast for very large data up to 100s or 1000s of GB</li></ul>
<br/>

 _Reply via <a href='https://app.reviewnb.com/exasol/data-science-examples/pull/10/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2020-02-24 12:11 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/LinearRegressionPrediction.py
> +        transformed_column = DataFrame(one_hot_encoder.transform(pandas_result_set_for_training.values))
fixed

2020-02-24 15:37 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/LinearRegressionPrediction.py
> +        y_column_ndarray = self.__get_y_column_ndarray(all_columns_train_data_frame, y_column_name, split)
done

2020-02-24 15:37 UTC, AnastasiiaSergienko commented on tutorials/python/scikit-learn/regression/LinearRegressionPrediction.py
> +        return self.__run_predict(regressor, x_columns_data_frame, y_column_ndarray)
done

2020-02-26 08:52 UTC, tkilias commented on tutorials/python/scikit-learn/regression/LinearRegressionPrediction.py
>      def start_regression(self, schema_name: str, table_name: str, x_columns_numerical_list: list,
I saw at a few points, that you use list as type hint. However, list is not a type hint it is a real type you can instantiate. Use typing.List instead, see here https://docs.python.org/3/library/typing.html#typing.List. With typing.List you can also specify the type of the elements in the list.

2020-02-26 09:00 UTC, tkilias commented on tutorials/python/scikit-learn/regression/linear_regression_udf
> +        connection = pyexasol.connect(dsn=connection_string.address, user=connection_string.user, password=connection_string.password, compression=True)
The UDF shouldn't use a connection to the database. So, in the next iteration we should use get_dataframe to iterate over the input data.

2024-09-27 09:27 UTC, tkilias commented
Close, because repo gets archived

2024-09-27 09:27 UTC, closed without merging