#35:Added the initial part of tutorial
exasol/data-science-examples pull request #36
Opened 2021-11-24 07:34 UTC by umitbuyuksahin

Fixes #35

2021-11-24 08:49 UTC, tkilias requested changes

2021-11-24 08:49 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +Exasol Sagemaker Extension enables you to develop an end-to-end machine
```suggestion
The Exasol Sagemaker Extension enables you to develop an end-to-end machine 
```

2021-11-24 08:49 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +learning project on data stored in Exasol using AWS SageMaker Autopilot service.
```suggestion
learning project on data stored in Exasol using the AWS SageMaker Autopilot service.
```

2021-11-24 08:49 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +The use-case handles a publicly available real-world data provided by a heavy
```suggestion
The use-case handles a publicly available real-world dataset provided by a heavy 
```

2021-11-24 08:49 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +truck manufacturer (see Use Case[#use-case]). With the
```suggestion
truck manufacturer (see (Use Case)[#use-case]). With the 
```

2021-11-24 08:49 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +of abstraction, SageMaker enables users to use Automated machine learning
```suggestion
of abstraction, SageMaker enables users to use an Automated machine learning 
```

2021-11-24 08:49 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +(AutoML) service, called Autopilot in AWS, that automatize the process of
```suggestion
(AutoML) service, called Autopilot in AWS, that automatizes the process of 
```

2021-11-24 08:49 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +Autopilot covers a  complete pipeline of developing end-to end machine learning
```suggestion
Autopilot covers a  complete pipeline of developing an end-to end machine learning 
```

2021-11-24 08:49 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +project, from raw data to deployable model. It is able to automatically build,
```suggestion
project, from raw data to a deployable model. It is able to automatically build, 
```

2021-11-24 08:49 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +Exasol Sagemaker Extension takes these advantages of AWS Autopilot and enables
```suggestion
The Exasol Sagemaker Extension takes these advantages of AWS Autopilot and enables 
```

2021-11-24 10:13 UTC, umitbuyuksahin commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +The dataset, provided by Scania CV AB, consists of real data .
@tkilias 
Do you think there is a need to put the python code that loads the datasets into the database ? Or I can assume these tables are ready and put reference to here [1]

[1] https://github.com/exasol/data-science-examples/blob/e85ce663a0474c60bd8d8700c9ae60c05c38f1e3/tutorials/machine-learning/python/sagemaker/LoadExampleDataIntoExasol.ipynb

2021-11-24 10:23 UTC, tkilias requested changes

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +BucketFS and then activate the uploaded container in Exasol. These pre-packages
```suggestion
BucketFS and then activate the uploaded container in Exasol. These pre-packaged
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +- The packaged sagemaker-extension project ****provides a command line tool to
```suggestion
- The sagemaker-extension python package ****provides a command line tool to 
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +    pip install exasol_sagemaker_extension.whl
```suggestion
    pip install https://github.com/exasol/sagemaker-extension/releases/download/<version>/exasol_sagemaker_extension-<version>-py3-none-any.whl
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +- The required libraries and dependencies of the SageMaker Extension project are
```suggestion
- The required libraries and dependencies of the Exasol SageMaker Extension are 
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +distributed into Exasol by uploading the pre-built SageMaker-Extension Language
```suggestion
distributed into Exasol by uploading the pre-built Exasol SageMaker-Extension Language 
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +Container to the BucketFS. You can upload  with any http(s) client that can send
```suggestion
Container to the BucketFS. You can upload it with any http(s) client that can send 
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +The following example uploads the pre-builtSageMaker-Extension Container to BucketFS through curl command, a http(s) client:
```suggestion
The following example uploads the pre-built SageMaker-Extension Container to BucketFS with the curl command, a http(s) client:
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +SageMaker-Extension. For more details please check
```suggestion
SageMaker-Extension. For more details, please check 
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +- You need to activate the uploaded container  for the whole system through
```suggestion
- You need to activate the uploaded container  for your session or the whole system through 
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +adjusting session parameter `SCRIPT_LANGUAGES`.  Please, keep in mind that
```suggestion
adjusting parameter `SCRIPT_LANGUAGES`.  Please, keep in mind that 
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +The installed SageMaker-extension package provides a command line tool, enabling
```suggestion
The installed SageMaker-extension python package provides a command line tool, enabling 
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +- Lua Scripts:
maybe add sql command to get the scripts from the metadata.

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +The SageMaker needs to make connection with your AWS SageMaker and AWS S3 bucket.
```suggestion
The Exasol SageMaker Extension needs to connect to AWS SageMaker and your AWS S3 bucket. 
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +For that it needs AWS credentials that has AWS Sagemaker Execution permissions.
```suggestion
For that, it needs AWS credentials that has AWS Sagemaker Execution permissions. 
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +The required credentials are AWS Access Key (Please check how to
don't use the term key pair, because it is used by AWS for ssh keys, only use access key, key, ...

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +In order for SageMaker-Extension to use access-key pair, you need to create
```suggestion
In order for the SageMaker-Extension to use the Access Key, you need to create 
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +Exasol `CONNECTION` object which securely stores your keys. For more information
```suggestion
an Exasol `CONNECTION` object which securely stores your keys. For more information, 
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +please check the [Create Connection in Exasol](https://docs.exasol.com/sql/create_connection.htm?Highlight=connection):
```suggestion
please check [Create Connection in Exasol](https://docs.exasol.com/sql/create_connection.htm?Highlight=connection):  
```

2021-11-24 10:23 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +Before creating the connection object, let's define the variables for the aws connection (Please note that you need to use your own credentials for below variables.)
```suggestion
Before creating the connection object, let's define the variables for the AWS connection (Please note, that you need to use your own credentials for below variables.)
```

2021-11-24 10:25 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +The dataset, provided by Scania CV AB, consists of real data .
we want this to be a end 2 end demo, so probably adding the import doesn't hurt

2021-11-25 08:24 UTC, umitbuyuksahin commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +```buildoutcfg
```suggestion
```python
```

2021-11-25 09:26 UTC, tkilias requested changes

2021-11-25 09:26 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +The dataset consists of data collected from heavy Scania trucks in everyday usage. The dataset includes two different class accroding to Air Pressure system (APS): (1) The positive class
```suggestion
The dataset consists of data collected from heavy Scania trucks in everyday usage. The dataset includes two different classes accroding to Air Pressure system (APS): (1) The positive class 
```

2021-11-25 09:26 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +In this use case,  it is proposed to develop a predictive machine learning model using SageMaker-Extension to classify failures according to whether they are related to APS, or not.
```suggestion
In this use case,  it is proposed to develop a predictive machine learning model using our SageMaker-Extension to classify failures according to whether they are related to APS, or not. 
```

2021-11-25 09:26 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +The following python script downloads the train and test datasets as csv files
```suggestion
The following python script downloads the train and test datasets as CSV files 
```

2021-11-25 09:26 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +securely exports the specified table from Exasol Database to your specified
```suggestion
securely exports the specified table from the Exasol Database to your specified 
```

2021-11-25 09:26 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +securely exports the specified table from Exasol Database to your specified
What do you mean securely? Do you mean that we use https as transport encryption, because I don't remember that we encrypt the data.

2021-11-25 09:26 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +AWS S3 bucket. This exporting operation is highly efficient, as it is performed
```suggestion
AWS S3 bucket. This export operation is highly efficient, as it is performed 
```

2021-11-25 09:26 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +![SME Training](./images/sme_training.png)
The image has the marking of a spell checker in the tittle, not sure if this was already in the original, if you can't fix it, maybe crop the title out.

2021-11-25 09:26 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +enables Autopilot to start a job with the  `JOB_NAME`. Please note that
```suggestion
enables Autopilot to start a job with the  `JOB_NAME`. Please note, that 
```

2021-11-25 09:26 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +This SQL command does not wait for the jobs to finish after calling Autopilot
```suggestion
This SQL command does not wait for the job to finish after calling Autopilot 
```

2021-11-25 09:46 UTC, umitbuyuksahin commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +![SME Training](./images/sme_training.png)
yes, I agree. In the worst-case I will crop it out

2021-11-26 08:34 UTC, umitbuyuksahin commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +) FROM IDA.TEST;
```suggestion
) FROM IDA.TEST
GROUP BY IPROC()

```

2021-11-26 10:59 UTC, tkilias approved these changes

2021-11-26 10:59 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +) FROM IDA.TEST;
yeah please include the GROUP BY and explain it shortly

2021-11-26 10:59 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +following SQL command to delete the endpoint and associated resources.
Maybe mention, that the UDF doesn't get removed, but doesn't work, until you restarted the Endpoint.

2021-11-26 10:59 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +of the Exasol SageMaker-Extension, and examined in detail that how it works on
```suggestion
of the Exasol SageMaker-Extension, and examined in detail how it works on 
```

2021-11-26 10:59 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +cli tool. The SQL commands which come with the deployment enable you to create
```suggestion
CLI tool. The SQL commands which come with the deployment enable you to create 
```

2021-11-26 10:59 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +cli tool. The SQL commands which come with the deployment enable you to create
Did we already explain somewhere what CLI means?

2021-11-26 10:59 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +the response is returned immediately. For more information please check the
```suggestion
the response is returned immediately. For more information, please check the 
```

2021-11-26 10:59 UTC, tkilias commented on tutorials/machine-learning/sagemaker-extension/tutorial.md
> +in mind that the `ENDPOINT_NAME` is also the name of the UDF script generated
```suggestion
in mind, that the `ENDPOINT_NAME` is also the name of the UDF script generated 
```

2021-11-26 10:59 UTC, tkilias requested changes
see my comments

2021-11-26 11:47 UTC, merged